### ISSUE TITLE
Please update the data.

### ISSUE THREAD

**Issue by Mapaler** [kiootic/pad-rikuu#1]
Your project is well done. But I couldn't initialize it when I tried myself. I hope you can update the latest data.

**Comment by Mapaler** [comment]
https://kiootic.github.io/pad-rikuu/#/cards/3930
I found a bug in the animation.
Dress hem in the lower left corner, Animation is not the same as in-game.

**Comment by kiootic** [comment]
Sorry, but this project is no longer maintained. Please use either [pad-resources](https://github.com/kiootic/pad-resources) project to obtain image data, or other projects to obtain other latest game data.
